'\" t
.\"     Title: ll2_read_entry
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2025-05-05
.\"    Manual: Programmer's Manual
.\"    Source: util-linux 2.41.1
.\"  Language: English
.\"
.TH "LL2_READ_ENTRY" "3" "2025-05-05" "util\-linux 2.41.1" "Programmer\*(Aqs Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
ll2_read_entry \- Reads one entry from database and returns that.
.SH "SYNOPSIS"
.sp
\fB#include <lastlog2.h>\fP
.sp
\fBint ll2_read_entry (struct ll2_context *\fIcontext\fP, const char *\fIuser\fP,
int64_t *\fIll_time\fP, char \fB\fItty\fP, char \fP\fIrhost\fP,
char \fB\fIpam_service\fP, char \fP\fIerror\fP);\fP
.SH "DESCRIPTION"
.sp
Reads the first entry from database, defined in \fIcontext\fP, for user \fIuser\fP.
If \fIcontext\fP is NULL, the default database, defined in \fILL2_DEFAULT_DATABASE\fP,
will be taken.
.sp
.if n .RS 4
.nf
.fam C
char    *error = NULL;
const   char *user = "root";
int64_t res_time;
char    *res_tty = NULL;
char    *res_rhost = NULL;
char    *res_service = NULL;

int ret = ll2_read_entry (NULL, user, &res_time, &res_tty, &res_rhost, &res_service, &error);
.fam
.fi
.if n .RE
.SH "RETURN VALUE"
.sp
Returns 0 on success, \-ENOMEM or \-1 on other failure.
\fIerror\fP contains an error string if the return value is \-1.
\fIerror\fP is not guaranteed to contain an error string, could also be NULL.
\fIerror\fP should be freed by the caller.
If lastlog2 database does not exist at all, the errno ENOENT is set
and can be checked.
.sp
The evaluated values are returned by \fIll_time\fP, \fItty\fP, \fIrhost\fP and \fIpam_service\fP.
.SH "AUTHORS"
.sp
Thorsten Kukuk (\c
.MTO "kukuk\(atsuse.de" "" ")"
.SH "SEE ALSO"
.sp
\fBlastlog2\fP(3),
\fBll2_new_context(3),
*ll2_unref_context(3),
*ll2_read_all\fP(3),
\fBll2_write_entry\fP(3),
\fBll2_update_login_time\fP(3),
\fBll2_remove_entry\fP(3),
\fBll2_rename_user\fP(3),
\fBll2_import_lastlog\fP(3)
.SH "REPORTING BUGS"
.sp
For bug reports, use the \c
.URL "https://github.com/util\-linux/util\-linux/issues" "issue tracker" "."
.SH "AVAILABILITY"
.sp
The \fBliblastlog2\fP library is part of the util\-linux package since version 2.40. It can be downloaded from \c
.URL "https://www.kernel.org/pub/linux/utils/util\-linux/" "Linux Kernel Archive" "."