static const AVInputFormat * const demuxer_list[] = {
    &ff_aac_demuxer,
    &ff_ac3_demuxer,
    &ff_asf_demuxer,
    &ff_avi_demuxer,
    &ff_dts_demuxer,
    &ff_eac3_demuxer,
    &ff_flac_demuxer,
    &ff_flv_demuxer,
    &ff_h264_demuxer,
    &ff_hevc_demuxer,
    &ff_m4v_demuxer,
    &ff_matroska_demuxer,
    &ff_mov_demuxer,
    &ff_mp3_demuxer,
    &ff_mpegps_demuxer,
    &ff_mpegts_demuxer,
    &ff_mpegvideo_demuxer,
    &ff_ogg_demuxer,
    &ff_vc1_demuxer,
    &ff_wav_demuxer,
    NULL };
