'\" t
.\"     Title: setpgid
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2025-02-26
.\"    Manual: User Commands
.\"    Source: util-linux 2.41
.\"  Language: English
.\"
.TH "SETPGID" "1" "2025-02-26" "util\-linux 2.41" "User Commands"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
setpgid \- run a program in a new process group
.SH "SYNOPSIS"
.sp
\fBsetpgid\fP [options] \fIprogram\fP [\fIarguments\fP]
.SH "DESCRIPTION"
.sp
\fBsetpgid\fP runs a program in a new process group.
.SH "OPTIONS"
.sp
\fB\-f\fP, \fB\-\-foreground\fP
.RS 4
Make the new process group the foreground process group of the controlling
terminal if there is a controlling terminal.
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Display help text and exit.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Display version and exit.
.RE
.SH "AUTHORS"
.sp
.MTO "daan.j.demeyer\(atgmail.com" "Daan De Meyer" ""
.SH "SEE ALSO"
.sp
\fBsetpgid\fP(2)
.SH "REPORTING BUGS"
.sp
For bug reports, use the \c
.URL "https://github.com/util\-linux/util\-linux/issues" "issue tracker" "."
.SH "AVAILABILITY"
.sp
The \fBsetpgid\fP command is part of the util\-linux package which can be downloaded from \c
.URL "https://www.kernel.org/pub/linux/utils/util\-linux/" "Linux Kernel Archive" "."