#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99
STOP=19

start_service() {
    procd_open_instance
    procd_set_param command "/usr/bin/zapret.sh" "start"
    procd_set_param stdout 0
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    /usr/bin/zapret.sh stop >/dev/null
}

reload_service() {
    /usr/bin/zapret.sh reload >/dev/null
}
